require("prototypes.entities")
require("prototypes.items")
-- require("prototypes.ammo")
require("prototypes.recipes")
require("prototypes.resources")
require("prototypes.signals")
require("prototypes.technology")